backend:
  name: test-repo

media_folder: "images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Content", name: "body", widget: "markdown" }
