backend:
  name: github
  repo: YasminKhawaja/test-site
  branch: main
  client_id: "Ov23li1n0ypqYhc1guPy"

media_folder: "images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "Content", name: "body", widget: "markdown" }
